require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Rails/LexicallyScopedActionFilter:
  Enabled: false
Style/GuardClause:
  Enabled: false

AllCops:
  # DisabledByDefault: true
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'public/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'features/**/*'
    - 'bin/**/*'
    - 'test/factories.rb'


Rails/SkipsModelValidations:
  Exclude:
    - 'app/models/folder.rb'
    - 'app/jobs/allocation_job.rb'
    - 'app/jobs/investment_percentage_holding_job.rb'
    - 'app/interactors/create_audit_trail.rb'
    - 'app/models/entity.rb'
    - 'app/jobs/offer_spa_job.rb'
Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/role.rb'
Naming/MethodName:
  Exclude:
    - 'app/models/investment.rb'
    - 'app/models/investor.rb'
Naming/AccessorMethodName:
  Exclude:
    - 'app/datatables/note_datatable.rb'

Lint/DuplicateBranch:
  Exclude:
    - 'app/helpers/investments_helper.rb'
Lint/MissingSuper:
  Exclude:
    - 'app/services/*'

Rails/OutputSafety:
  Exclude:
    - 'config/initializers/client_side_validations.rb'
Style/OptionalBooleanParameter:
  Exclude:
    - 'app/helpers/investments_helper.rb'
    - 'app/mailers/email_currency_helper.rb'
# Metrics Cops
Metrics/CyclomaticComplexity:
  Max: 10
  Enabled: true
Metrics/PerceivedComplexity:
  Exclude:
    - 'app/models/user.rb'
    - 'app/controllers/tasks_controller.rb'
Metrics/ClassLength:
  Description: 'Avoid classes longer than 100 lines of code.'
  Max: 170
  Enabled: true

Metrics/ModuleLength:
  Description: 'Avoid modules longer than 100 lines of code.'
  Max: 100
  Enabled: true

Metrics/ParameterLists:
  Description: 'Pass no more than four parameters into a method.'
  Max: 4
  Enabled: true

Metrics/MethodLength:
  Description: 'Avoid methods longer than 5 lines of code.'
  StyleGuide: '<https://github.com/bbatsov/ruby-style-guide#short-methods>'
  Max: 25
  Enabled: true
  Exclude:
    - 'app/controllers/access_rights_controller.rb'
  
Metrics/BlockLength:
  CountComments: false
  Max: 15
  Exclude:
    - 'app/views/secondary_sales/download.xlsx.axlsx'
    - 'app/jobs/import_upload_job.rb'
    - 'app/jobs/investment_percentage_holding_job.rb'
  IgnoredMethods:
    - context
    - describe
    - it
    - shared_examples
    - shared_examples_for
    - namespace
    - draw
    - configure
    - group    
    - included