# Generated by Roo Code
# Reference: kpi_portco_upload.md
class GeneratePeriodicKpiReportsJob < ApplicationJob
  queue_as :default

  def perform
    Entity.joins(:entity_setting).where_permissions(:enable_kpis).find_each do |entity|
      settings = entity.entity_setting
      next if settings.kpi_reminder_frequency.blank?

      # Logic to determine if we should create a report today
      # based on kpi_reminder_frequency and kpi_reminder_before
      # This is a simplified version of the trigger logic
      target_date = calculate_target_date(settings.kpi_reminder_frequency)
      trigger_date = target_date - (settings.kpi_reminder_before || 0).days

      # Reference: kpi_portco_upload.md
      # For testing, we might want to bypass this check
      next unless Time.zone.today >= trigger_date

      entity.investors.portfolio_companies.find_each do |portco|
        KpiReportCreateShell.wtf?(entity: entity, portco: portco, as_of: target_date, period: settings.kpi_reminder_frequency)
      end
    end
  end

  private

  def calculate_target_date(frequency)
    case frequency
    when "Monthly"
      Time.zone.today.end_of_month
    when "Quarterly"
      Time.zone.today.end_of_quarter
    else
      Time.zone.today
    end
  end
end
